name: dev_bardic
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/gitvex/bardicinspiration_dev:latest
    environment:
      - SERVICE_FQDN_APP_3000
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - CRON_SECRET=${CRON_SECRET}
    restart: always
    networks:
        - coolify

networks:
  coolify:
    external: true