version: '3'

services:
  bardicInspiration_dev:
    image: ghcr.io/gitvex/bardicinspiration_dev:latest

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

    ports:
      - "3000:3000"
    restart: always
