services:
  bardicInspiration_prod:
    image: ghcr.io/gitvex/bardicinspiration_prod:latest

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

    ports:
      - "8080:3000"
    restart: always
